name: Package using PyInstaller
on:
  push:
  workflow_dispatch:

jobs:
  build:
    env:
      dist-path: dist/OpenSeeFace
      python-version: '3.13'
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - identifier: windows
            runner: windows-latest
          - identifier: linux
            runner: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python-version }}
          cache: 'poetry'
      - name: Setup MSVC
        if: matrix.identifier == 'windows'
        shell: cmd
        run: |
          choco install vcredist140

          xcopy c:\Windows\System32\msvcp140.dll .
          xcopy c:\Windows\System32\vcomp140.dll .
          xcopy c:\Windows\System32\concrt140.dll .
          xcopy c:\Windows\System32\vccorlib140.dll .
      - name: Setup PyEnv
        run: |
          poetry install

      - name: Build
        run: |
          poetry run pyinstaller --onedir --clean --noconfirm facetracker.py
          cp -r models dist/facetracker/models
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix.identifier
          path: dist # Add the parent directory to prevent a tarbomb
